name: GitHub Actions Docker Demo
run-name: ${{ github.actor }} testing GitHub Actions
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Run Docker container
      run: |
        docker run -v test alpine 
    
    - name: Run arbitrary code inside the container
      run: |
        docker exec test ls
