name: GitHub Actions Docker Demo
run-name: ${{ github.actor }} testing GitHub Actions
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Dockerfile from external repository
      run: |
        curl -LJO https://raw.githubusercontent.com/external/repo/main/path/to/dockerfile
      working-directory: path/to/your/dockerfile/directory

    - name: Build Docker image
      run: |
        docker build -t my-docker-image .
     
    - name: Run Docker container
      run: |
        docker run -d --name my-container my-docker-image
    
    - name: Run arbitrary code inside the container
      run: |
        docker exec my-container ./build-my-application
