name: GitHub Actions Docker Demo
run-name: ${{ github.actor }} testing GitHub Actions
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Run Docker container
      run: |
        docker run -it --rm alpine /bin/ash
    
    - name: Run arbitrary code inside the container
      run: |
        docker exec my-container ls
