name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job status is ${{ job.status }}."
